apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app-1
spec:
  containers:
    - name: my-app-container
      image: busybox
      command:
        - "sh"
        - "-c"
        - "echo Hello Kubernetes! && sleep 3600"
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
