apiVersion: v1
kind: Service
metadata:
  labels:
    sandbox: ckad-7-1
  namespace: acg-ckad
  name: my-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
    sandbox: ckad-7-1
  type: ClusterIP
