version: 3

vars:
  CHAINSAW_CONTEXT: k3d-aok
  CHAINSAW_VERSION: v0.2.12

tasks:
  default:
    # https://clig.dev/#help
    desc: Display a concise help text by default.
    silent: true
    cmd: task --list-all

  test:
    desc: Test the operator's functionality with Kyverno Chainsaw.
    requires:
      vars:
        - CHAINSAW_CONTEXT
        - CHAINSAW_VERSION
    preconditions:
      - sh: >-
          currCtx=$(kubectl config view --template='{{`{{index . "current-context"}}`}}')
          && [[ $currCtx == "{{.CHAINSAW_CONTEXT}}" ]]
        msg: The current context selected by kubectl does not match '{{.CHAINSAW_CONTEXT}}'.
    dir: '{{.TASKFILE_DIR}}/test'
    cmd: >-
      docker run
      --env=KUBECONFIG=/etc/kubeconfig/config
      --network=host
      --rm
      --volume=${HOME}/.kube/:/etc/kubeconfig/
      --volume=${PWD}/:/chainsaw/
      ghcr.io/kyverno/chainsaw:{{.CHAINSAW_VERSION}}
      test /chainsaw
      --config /chainsaw/chainsaw-config.yaml
