version: 3

tasks:
  default: task --list-all

  schema:update:
    desc: Update the JSON Schema file for AdventPuzzle, by exporting the CRD from an ephemeral cluster.
    interactive: true
    dir: '{{.TASKFILE_DIR}}'
    cmd: ../crd-x/update-schema.sh
