version: 3

run: once

vars:
  GIT_ROOT:
    sh: git -C "{{.TASKFILE_DIR}}" rev-parse --show-toplevel

  KIND_CLUSTER_NAME: '{{default "aok" (env "KIND_CLUSTER_NAME")}}'
  KIND_IMAGE_VERSION: v1.33.4
  KIND_IMAGE: kindest/node:{{.KIND_IMAGE_VERSION}}

  KUBECTL_CONTEXT: kind-{{.KIND_CLUSTER_NAME}}

  SCRIPT_TMP_DIR: '{{joinPath .GIT_ROOT "scripts/tmp"}}'

  REGISTRY_BASE: ghcr.io/jlucktay
  CONTROLLER_IMAGE: '{{joinPath .REGISTRY_BASE "aok-controller"}}'
  CONTROLLER_IMAGE_ID_PATH: '{{joinPath .SCRIPT_TMP_DIR "controller-image-id"}}'
  CRD_X_IMAGE: '{{joinPath .REGISTRY_BASE "crd-x"}}'

  KUBECONFIG: '{{joinPath .SCRIPT_TMP_DIR "kubeconfig"}}'
  SCHEMAS: '{{joinPath .GIT_ROOT "adventofcode/schema"}}'

  CHAINSAW_VERSION: v0.2.13

env:
  GIT_ROOT: '{{.GIT_ROOT}}'
  KIND_CLUSTER_NAME: '{{.KIND_CLUSTER_NAME}}'
  KUBECTL_CONTEXT: '{{.KUBECTL_CONTEXT}}'

tasks:
  default:
    # https://clig.dev/#help
    desc: Display a concise help text by default.
    silent: true
    cmd: task --list-all

  cluster-create:
    desc: Create a local cluster with kind.
    requires:
      vars:
        - KIND_CLUSTER_NAME
        - KIND_IMAGE
    preconditions:
      - sh: command -v kind
        msg: The 'kind' command is not installed or available on your PATH.
      - sh: command -v rg
        msg: The 'rg' command is not installed or available on your PATH.
    status:
      - kind get clusters | rg '^{{.KIND_CLUSTER_NAME}}$'
    cmd: kind create cluster --image {{.KIND_IMAGE}} --name {{.KIND_CLUSTER_NAME}}

  cluster-await:
    desc: Wait for the local cluster to be ready.
    requires:
      vars:
        - GIT_ROOT
        - # Used in the shell script
          KUBECTL_CONTEXT
    deps:
      - task: cluster-create
    preconditions:
      - sh: command -v kubectl
        msg: The 'kubectl' command is not installed or available on your PATH.
    cmd: '{{.GIT_ROOT}}/scripts/task.cluster-await.sh'

  apply-crds:
    desc: Apply the CRDs to the cluster.
    requires:
      vars:
        - GIT_ROOT
        - KUBECTL_CONTEXT
    deps:
      - task: cluster-await
    status:
      - kubectl --context="{{.KUBECTL_CONTEXT}}" diff --filename="{{.GIT_ROOT}}/adventofcode/config/crd/*.yaml"
    cmd: kubectl --context="{{.KUBECTL_CONTEXT}}" apply --filename="{{.GIT_ROOT}}/adventofcode/config/crd/*.yaml"

  controller-build:
    desc: Build the controller image.
    requires:
      vars:
        - CONTROLLER_IMAGE
        - CONTROLLER_IMAGE_ID_PATH
        - GIT_ROOT
    preconditions:
      - sh: command -v docker
        msg: The 'docker' command is not installed or available on your PATH.
    vars:
      CONTROLLER_IMAGE_ID: '{{.CONTROLLER_IMAGE}}:{{uuid}}'
    method: checksum
    sources:
      - '{{.GIT_ROOT}}/adventofcode/**/*'
      - exclude: '{{.GIT_ROOT}}/adventofcode/config/cluster/**/*.yaml'
      - exclude: '{{.GIT_ROOT}}/adventofcode/test/**/*'
    generates:
      - '{{.CONTROLLER_IMAGE_ID_PATH}}'
    dir: '{{.GIT_ROOT}}/adventofcode'
    cmds:
      - mkdir -p "{{osDir .CONTROLLER_IMAGE_ID_PATH}}"
      - docker build --tag "{{.CONTROLLER_IMAGE_ID}}" .
      - echo "{{.CONTROLLER_IMAGE_ID}}" > "{{.CONTROLLER_IMAGE_ID_PATH}}"

  controller-load:
    desc: Load the controller image into the local cluster.
    requires:
      vars:
        - CONTROLLER_IMAGE_ID_PATH
        - KIND_CLUSTER_NAME
    deps:
      - task: cluster-await
      - task: controller-build
    cmd: kind load docker-image "$(< "{{.CONTROLLER_IMAGE_ID_PATH}}")" --name="{{.KIND_CLUSTER_NAME}}"

  controller-install:
    desc: Install the controller into the local cluster.
    requires:
      vars:
        - CONTROLLER_IMAGE_ID_PATH
        - GIT_ROOT
    deps:
      - task: controller-load
    cmds:
      - >-
        CID="$(< "{{.CONTROLLER_IMAGE_ID_PATH}}")"
        yq eval --inplace --prettyPrint
        '(.spec.template.spec.containers[] | select(.name == "aok-controller") | .image) = strenv(CID)'
        "{{.GIT_ROOT}}/adventofcode/config/cluster/2-deployment/deployment.yaml"
      - for:
          - config/crd
          - config/cluster/0-namespace
          - config/cluster/1-rbac
          - config/cluster/2-deployment
        task: controller-install-internal
        vars:
          SPEC_DIR: '{{.ITEM}}'

  controller-install-internal:
    desc: Install the spec(s) in the given directory into the local cluster.
    internal: true
    run: when_changed
    requires:
      vars:
        - GIT_ROOT
        - KUBECTL_CONTEXT
        - SPEC_DIR
    status:
      - kubectl --context="{{.KUBECTL_CONTEXT}}" diff --filename="{{.GIT_ROOT}}/adventofcode/{{.SPEC_DIR}}/*.yaml"
    cmd: kubectl --context="{{.KUBECTL_CONTEXT}}" apply --filename="{{.GIT_ROOT}}/adventofcode/{{.SPEC_DIR}}/*.yaml"

  controller-await:
    desc: Wait for the controller to be ready.
    requires:
      vars:
        - GIT_ROOT
        - KUBECTL_CONTEXT
    deps:
      - task: controller-install
    cmds:
      - kubectl --context="{{.KUBECTL_CONTEXT}}" get --filename="{{.GIT_ROOT}}/adventofcode/config/cluster/2-deployment/*.yaml"
      - kubectl --context="{{.KUBECTL_CONTEXT}}" wait --filename="{{.GIT_ROOT}}/adventofcode/config/cluster/2-deployment/*.yaml" --for=condition=Available

  controller-bounce:
    desc: Restart the controller deployment in the local cluster.
    requires:
      vars:
        - GIT_ROOT
        - KUBECTL_CONTEXT
    deps:
      - task: controller-install
    cmds:
      - kubectl --context="{{.KUBECTL_CONTEXT}}" rollout restart --filename="{{.GIT_ROOT}}/adventofcode/config/cluster/2-deployment/*.yaml"
      - task: controller-await

  crd-x-build:
    desc: Build the worker image.
    requires:
      vars:
        - CRD_X_IMAGE
        - GIT_ROOT
    preconditions:
      - sh: command -v docker
        msg: The 'docker' command is not installed or available on your PATH.
    method: checksum
    sources:
      - '{{.GIT_ROOT}}/crd-x/**/*'
    dir: '{{.GIT_ROOT}}/crd-x'
    cmd: docker build --tag "{{.CRD_X_IMAGE}}" .

  crd-x-kubeconfig:
    desc: Set up and transform a kubeconfig file with the server address of the local cluster.
    requires:
      vars:
        - GIT_ROOT
        - KIND_CLUSTER_NAME
    vars:
      # This will be a container-to-container connection on the same network, using the 'docker run --network=...' flag.
      # The worker container can use the name of the control plane server container, and will be able to resolve its IP address.
      # The port is not the randomised port that Docker externalises, but that of the control plane itself inside the server container.
      # Thank you: https://rancher-users.slack.com/archives/CHM1EB3A7/p1745957501473809
      KIND_SERVER: https://{{.KIND_CLUSTER_NAME}}-control-plane:6443
    deps:
      - task: cluster-create
    preconditions:
      - sh: command -v kubectl
        msg: The 'kubectl' command is not installed or available on your PATH.
      - sh: command -v yq
        msg: The 'yq' command is not installed or available on your PATH.
    cmds:
      - mkdir -p "{{osDir .KUBECONFIG}}"
      - >-
        kubectl --context="{{.KUBECTL_CONTEXT}}" config view --minify --raw
        | yq '.clusters[].cluster.server = "{{.KIND_SERVER}}"' > "{{.KUBECONFIG}}"

  schema-update:
    desc: Update the JSON Schema files for Kinds in the adventofcode.jlucktay.dev Group, by passing the CRDs through the local cluster.
    requires:
      vars:
        - CRD_X_IMAGE
        - KUBECONFIG
        - SCHEMAS
    deps:
      - task: apply-crds
      - task: crd-x-build
      - task: crd-x-kubeconfig
    cmds:
      - mkdir -p "{{.SCHEMAS}}"
      - >-
        docker run
        --network="kind"
        --rm
        --volume="{{.KUBECONFIG}}:/root/.kube/config:ro"
        --volume="{{.SCHEMAS}}:/schema/:rw"
        "{{.CRD_X_IMAGE}}"

  test:
    desc: Test the operator's functionality with Kyverno Chainsaw.
    requires:
      vars:
        - CHAINSAW_VERSION
        - GIT_ROOT
        - KUBECONFIG
    deps:
      - task: apply-crds
      - task: crd-x-kubeconfig
      - task: controller-await
    preconditions:
      - sh: command -v docker
        msg: The 'docker' command is not installed or available on your PATH.
    dir: '{{.GIT_ROOT}}/adventofcode/test'
    cmd: >-
      docker run
      --env=KUBECONFIG=/etc/kubeconfig/config
      --network="kind"
      --rm
      --volume={{.KUBECONFIG}}:/etc/kubeconfig/config
      --volume=${PWD}/:/chainsaw/
      ghcr.io/kyverno/chainsaw:{{.CHAINSAW_VERSION}}
      test /chainsaw
      --config /chainsaw/chainsaw-config.yaml

  down:
    desc: Tear down the local cluster, remove any built images, and tidy up the temporary kubeconfig.
    deps:
      - task: down-cluster
      - task: down-docker
      - task: down-kubeconfig

  down-cluster:
    desc: Tear down the local cluster.
    requires:
      vars:
        - KIND_CLUSTER_NAME
    cmd: kind delete cluster --name {{.KIND_CLUSTER_NAME}}

  down-docker:
    desc: Remove any local built Docker images.
    requires:
      vars:
        - CONTROLLER_IMAGE
        - CONTROLLER_IMAGE_ID_PATH
    cmds:
      - >-
        docker images --filter=reference="{{.CONTROLLER_IMAGE}}" --no-trunc --quiet
        | sort --ignore-case --unique
        | xargs docker rmi --force
      - rm -f "{{.CONTROLLER_IMAGE_ID_PATH}}"

  down-kubeconfig:
    desc: Tidy up the temporary kubeconfig.
    requires:
      vars:
        - KUBECONFIG
    cmd: rm -f "{{.KUBECONFIG}}"
