---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aok-controller
  namespace: aok-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aok-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aok-controller
    spec:
      serviceAccountName: aok-controller
      containers:
        - name: aok-controller
          image: ghcr.io/jlucktay/aok-controller
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              memory: 1Gi
