apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-volume-pod
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: ["sh", "-c", "echo $(cat /etc/config/myKey) && sleep 3600"]
      volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map
