apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
spec:
  containers:
    - name: my-app-container
      image: busybox
      # command: ["sh", "-c", "echo $(MY_VAR) && sleep 3600"] # Kubernetes substitution syntax
      # command: ["sh", "-c", "env && sleep 3600"]
      command: ["sh", "-c", 'echo "MY_VAR is ''$MY_VAR''" && sleep 3600'] # shell syntax
      env:
        - name: MY_VAR
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: myKey
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
