apiVersion: v1
kind: Pod
metadata:
  name: my-liveness-pod
spec:
  containers:
    - name: my-app-container
      image: busybox
      command:
        ["sh", "-c", "while true; do echo Hello, Kubernetes!; sleep 3600; done"]
      livenessProbe:
        exec:
          command:
            - echo
            - testing
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
