apiVersion: v1
kind: Pod
metadata:
  name: my-securitycontext-pod
spec:
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
    - name: my-app-container
      image: busybox
      command: ["sh", "-c", "cat /message/message.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /message
          name: message-volume
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
  volumes:
    - name: message-volume
      hostPath:
        path: /etc/message
