apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  labels:
    sandbox: ckad-6-4
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        sandbox: ckad-6-4
    spec:
      template:
        metadata:
          labels:
            sandbox: ckad-6-4
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
          restartPolicy: OnFailure
