apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  labels:
    sandbox: ckad-6-4
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        sandbox: ckad-6-4
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Never
  backoffLimit: 3
