apiVersion: v1
kind: Pod
metadata:
  labels:
    name: myapp
    sandbox: ckad-8-1
  name: volume-pod
  namespace: acg-ckad
spec:
  containers:
    - command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      image: busybox
      name: busybox
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
      volumeMounts:
        - mountPath: /tmp/storage
          name: my-volume
  volumes:
    - emptyDir: {}
      name: my-volume
