apiVersion: v1
kind: Pod
metadata:
  name: my-args-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-app-container
      image: busybox
      command:
        - "echo"
      args:
        - "This is my custom argument"
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
  restartPolicy: Never
