apiVersion: v1
kind: Pod
metadata:
  name: my-containerport-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-app-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
