apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx:1
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
    - name: busybox-sidecar
      image: busybox
      command: ["sh", "-c", "while true; do sleep 30; done;"]
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
