apiVersion: v1
kind: Pod
metadata:
  name: resource-consumer-small
spec:
  containers:
    - name: resource-consumer
      image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
    - name: curl-sidecar
      image: curlimages/curl:7.73.0
      command:
        [
          /bin/sh,
          -c,
          'until curl localhost:8080/ConsumeCPU -d "millicores=100&durationSec=3600"; do sleep 5; done && sleep 3700',
        ]
      resources:
        limits:
          cpu: "1000m"
          memory: "256Mi"
