---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: answers.adventofcode.jlucktay.dev

spec:
  group: adventofcode.jlucktay.dev
  names:
    kind: Answer
    plural: answers
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Answer represents the answer to an Advent of Code (https://adventofcode.com) puzzle, which the AOK operator has (attempted to) solve.
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            spec:
              type: object
              description: spec describes how the user wants the resources to appear.
              properties:
                year:
                  type: integer
                  description: Year will be between 2015 and that of the most recent/current December (inclusive).
                  minimum: 2015
                  maximum: 2024
                day:
                  type: integer
                  description: Day ranges from 1 to 31; the length of December.
                  minimum: 1
                  maximum: 31
                answer:
                  type: string
                  description: Answer to the day's puzzle.
              required:
                - year
                - day
                - answer
          required:
            - metadata
            - spec
