---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: adventpuzzles.k8s.jlucktay.dev

spec:
  group: k8s.jlucktay.dev
  names:
    kind: AdventPuzzle
    plural: adventpuzzles
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: AdventPuzzle represents an Advent of Code puzzle, that the AOK operator will attempt to answer.
          properties:
            spec:
              type: object
              properties:
                year:
                  type: integer
                  description: Year will be between 2015 and that of the most recent/current December (inclusive).
                  minimum: 2015
                  maximum: 2024
                day:
                  type: integer
                  description: Day ranges from 1 to 31; the length of December.
                  minimum: 1
                  maximum: 31
                input:
                  type: string
                  description: Input of the day's puzzle.
