apiVersion: v1
kind: Pod
metadata:
  name: my-annotation-pod
  annotations:
    owner: jlucktay
    git-commit: 9ccc0f6ba6e7d2a82bc0d0956e0f81f9c7071b2b
  labels:
    sandbox: ckad-6-1
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
