apiVersion: v1
kind: Pod
metadata:
  name: my-development-label-pod
  labels:
    app: my-app
    environment: development
    sandbox: ckad-6-1
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
