---
apiVersion: v1
kind: Service

metadata:
  name: nginx-parallel
  labels:
    app: nginx-parallel

spec:
  ports:
    - port: 80
      name: web-parallel
  clusterIP: None
  selector:
    app: nginx-parallel
---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nginx-parallel

spec:
  serviceName: nginx-parallel
  podManagementPolicy: Parallel
  replicas: 5
  selector:
    matchLabels:
      app: nginx-parallel
  template:
    metadata:
      labels:
        app: nginx-parallel
    spec:
      containers:
        - name: nginx-parallel
          image: nginx:1.29
          ports:
            - containerPort: 80
              name: web-parallel
          volumeMounts:
            - name: www-parallel
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
  volumeClaimTemplates:
    - metadata:
        name: www-parallel
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
